require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LibraryObjectivesController do

  # This should return the minimal set of attributes required to create a valid
  # LibraryObjective. As you add validations to LibraryObjective, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all library_objectives as @library_objectives" do
      library_objective = LibraryObjective.create! valid_attributes
      get :index
      assigns(:library_objectives).should eq([library_objective])
    end
  end

  describe "GET show" do
    it "assigns the requested library_objective as @library_objective" do
      library_objective = LibraryObjective.create! valid_attributes
      get :show, :id => library_objective.id.to_s
      assigns(:library_objective).should eq(library_objective)
    end
  end

  describe "GET new" do
    it "assigns a new library_objective as @library_objective" do
      get :new
      assigns(:library_objective).should be_a_new(LibraryObjective)
    end
  end

  describe "GET edit" do
    it "assigns the requested library_objective as @library_objective" do
      library_objective = LibraryObjective.create! valid_attributes
      get :edit, :id => library_objective.id.to_s
      assigns(:library_objective).should eq(library_objective)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LibraryObjective" do
        expect {
          post :create, :library_objective => valid_attributes
        }.to change(LibraryObjective, :count).by(1)
      end

      it "assigns a newly created library_objective as @library_objective" do
        post :create, :library_objective => valid_attributes
        assigns(:library_objective).should be_a(LibraryObjective)
        assigns(:library_objective).should be_persisted
      end

      it "redirects to the created library_objective" do
        post :create, :library_objective => valid_attributes
        response.should redirect_to(LibraryObjective.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved library_objective as @library_objective" do
        # Trigger the behavior that occurs when invalid params are submitted
        LibraryObjective.any_instance.stub(:save).and_return(false)
        post :create, :library_objective => {}
        assigns(:library_objective).should be_a_new(LibraryObjective)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LibraryObjective.any_instance.stub(:save).and_return(false)
        post :create, :library_objective => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested library_objective" do
        library_objective = LibraryObjective.create! valid_attributes
        # Assuming there are no other library_objectives in the database, this
        # specifies that the LibraryObjective created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LibraryObjective.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => library_objective.id, :library_objective => {'these' => 'params'}
      end

      it "assigns the requested library_objective as @library_objective" do
        library_objective = LibraryObjective.create! valid_attributes
        put :update, :id => library_objective.id, :library_objective => valid_attributes
        assigns(:library_objective).should eq(library_objective)
      end

      it "redirects to the library_objective" do
        library_objective = LibraryObjective.create! valid_attributes
        put :update, :id => library_objective.id, :library_objective => valid_attributes
        response.should redirect_to(library_objective)
      end
    end

    describe "with invalid params" do
      it "assigns the library_objective as @library_objective" do
        library_objective = LibraryObjective.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LibraryObjective.any_instance.stub(:save).and_return(false)
        put :update, :id => library_objective.id.to_s, :library_objective => {}
        assigns(:library_objective).should eq(library_objective)
      end

      it "re-renders the 'edit' template" do
        library_objective = LibraryObjective.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LibraryObjective.any_instance.stub(:save).and_return(false)
        put :update, :id => library_objective.id.to_s, :library_objective => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested library_objective" do
      library_objective = LibraryObjective.create! valid_attributes
      expect {
        delete :destroy, :id => library_objective.id.to_s
      }.to change(LibraryObjective, :count).by(-1)
    end

    it "redirects to the library_objectives list" do
      library_objective = LibraryObjective.create! valid_attributes
      delete :destroy, :id => library_objective.id.to_s
      response.should redirect_to(library_objectives_url)
    end
  end

end
